audit_header: false
title: Real Estate Video Blog with John Graham
description: Our mission at The Legacy Group Network is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Legacy Group Network, your professional Real Estate Agents.
show_custom_links: true
custom_links:
  - title: About
    url: /about/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: John Graham
  title:
  license_number:
  about_markdown: |
    One of Spokane’s top selling real estate teams, the Legacy Group was ranked in the top 220 real estate companies in the nation (Wall Street Journal of Business-2013).

    Owner/lead agent Seth Maefsky specializes in listing and selling homes, and ranks in the top 3% of REALTORS in Spokane. The Legacy Group uses the latest technologies, market research and business strategies while tailoring their approach to your real estate needs. If you’re looking to buy or sell real estate, the Legacy Group is here to help!
  brand: The Legacy Group Network
  brokerage:
  market: Spokane and Miami
  address: 205 W Indiana Ave, Spokane, WA 99205
  phone: 509-922-7355
  phone_type:
  phone2:
  phone2_type:
  email: info@thelegacygroupnetwork.com
  url: http://www.thelegacygroupnetwork.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.thelegacygroupnetwork.com/evaluation
  second_CTA_text: See Listings
  second_CTA_URL: https://www.thelegacygroupnetwork.com/search?zoom=10&rect=null&layoutType=map&mapType=list&page=1&listingSort=RELEVANCE&pageSize=24
  third_CTA_text: Sell My Home
  third_CTA_URL: https://www.thelegacygroupnetwork.com/sell

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.thelegacygroupnetwork.com/evaluation

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Home?"
    CTA_text2: "Search the entire MLS for your  home."
    CTA_link_text2: "See Listings"
    CTA_url2: https://www.thelegacygroupnetwork.com/search?zoom=10&rect=null&layoutType=map&mapType=list&page=1&listingSort=RELEVANCE&pageSize=24

third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/003.jpg
    CTA_title3: "Sell My Home"
    CTA_text3: "We love working with sellers and look forward to sharing our home-selling plan with you!"
    CTA_link_text3: "Learn More"
    CTA_url3: https://www.thelegacygroupnetwork.com/sell

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheLegacyGroupKellerWilliams
  linkedin_url:
  youtube_url: https://www.youtube.com/user/LegacyGroupspokane1
  twitter_url: https://twitter.com/LegacySpokaneRE
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/sethm4/
  trulia_url: https://www.trulia.com/profile/seth-maefsky-the-legacy-group-network-agent-spokane-wa-zgq1ljd6/overview
  yelp_url: https://www.yelp.com/biz/the-legacy-group-spokane
  podcast_url:

podcast:
  title: 'Real Estate Podcast with John Graham'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Legacy Group Network - your professional Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Spokane and Miami, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'John Graham'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#333333'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
